const data = {
    products: [{
        _id: 1,
        name: 'Nike slim shirt',
        category: 'Shirts',
        image: '/images/p1.jpg',
        price: 120,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'This is good',
    },
    {
        _id: 2,
        name: 'ASOS',
        category: 'Shirts',
        image: '/images/p1.jpg',
        price: 220,
        brand: 'Nike',
        rating: 0,
        numReviews: 10,
        description: 'This is good',
    },
    {
        _id: 3,
        name: 'Nike slim shirt',
        category: 'Shirts',
        image: '/images/p1.jpg',
        price: 120,
        brand: 'Nike',
        rating: 3,
        numReviews: 10,
        description: 'This is good',
    },
    {
        _id: 4,
        name: 'BSOS',
        category: 'Shirts',
        image: '/images/p1.jpg',
        price: 120,
        brand: 'Nike',
        rating: 1.5,
        numReviews: 10,
        description: 'This is good',
    },
    {
        _id: 5,
        name: 'CSOS',
        category: 'Shirts',
        image: '/images/p1.jpg',
        price: 120,
        brand: 'Nike',
        rating: 3.5,
        numReviews: 10,
        description: 'This is good',
    },
    {
        _id: 6,
        name: 'Nike slim shirt',
        category: 'Shirts',
        image: '/images/p1.jpg',
        price: 120,
        brand: 'Nike',
        rating: 5,
        numReviews: 10,
        description: 'This is good',
    },
    {
        _id: 7,
        name: 'Nike slim shirt',
        category: 'Shirts',
        image: '/images/p1.jpg',
        price: 120,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'This is good',
    },
    
]
}

export default data;